FROM ubuntu:22.04
WORKDIR /app
RUN apt-get update
RUN apt-get install -y python3.11
#RUN apt-get install -y python3-pip 
COPY requirements.txt requirements.txt
#RUN pip3 install -r requirements.txt
COPY *.py . 
